services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules
    environment:
      DATABASE_URL: mysql://root:root@db:3306/nest
    command: sh -c "npm install && npm run start:dev"

  db:
    image: mysql:8.0.30-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest
    ports:
      - 3306:3306
    # volumes:
    #   - ./.docker/dbdata:/var/lib/mysql
